apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: apiserver-cache

resources:
  - namespace.yaml
  - configmap.yaml
  - deployment.yaml
  - service.yaml

images:
  - name: apiserver-cache
    newTag: latest
